baseurl = "https://angelakwak.giesen.org"
title = "The knight bus to Second Life"
author = "Angela Kwak"
copyright = "Copyright © 2008–2019, Angela Kwak,k  all rights reserved."
canonifyurls = true
paginate = 3
theme = "silhouette-hugo"

pygmentsUseClasses=true

#disqusShortname = ""
#googleAnalytics = ""

[params]
author = ""
introDescription = ""
contentSharing = "Feel free to share this content non commercially, Attribution-NonCommercial-ShareAlike"

[social]
# instagram = ""
# linkedin = ""
# twitter = ""

